"""empty message

Revision ID: 3674636759bd
Revises: 
Create Date: 2024-01-30 14:46:15.995717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '3674636759bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ballparks',
                    sa.Column('venue_id', sa.Integer(), nullable=False),
                    sa.Column('venue_name', sa.String(), nullable=True),
                    sa.Column('venue_location', postgresql.JSON(
                        astext_type=Text()), nullable=True),
                    sa.PrimaryKeyConstraint('venue_id')
                    )
    op.create_table('users',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('password', sa.String(), nullable=True),
                    sa.Column('first_year', sa.DateTime(), server_default=sa.text(
                        '(CURRENT_TIMESTAMP)'), nullable=True),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    op.create_table('games',
                    sa.Column('gamePk', sa.Integer(), nullable=False),
                    sa.Column('date', sa.String(), nullable=True),
                    sa.Column('venue_id', sa.String(), nullable=True),
                    sa.Column('game_data', postgresql.JSON(
                        astext_type=Text()), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['venue_id'], ['ballparks.venue_id'], ),
                    sa.PrimaryKeyConstraint('gamePk')
                    )
    op.create_table('usergames',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('gamePk', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['gamePk'], ['games.gamePk'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usergames')
    op.drop_table('games')
    op.drop_table('users')
    op.drop_table('ballparks')
    # ### end Alembic commands ###
