"""empty message

Revision ID: 811ab47b8a2e
Revises: d40781e421ba
Create Date: 2024-01-29 22:43:44.605452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811ab47b8a2e'
down_revision = 'd40781e421ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_games_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_games_association',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('gamePk', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['gamePk'], ['user_games.gamePk'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'gamePk')
    )
    # ### end Alembic commands ###
